# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bokete-practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bokete-practice

pod 'SwiftyJSON'
pod 'Alamofire'
pod 'SDWebImage'

end
